# Generated by Django 4.2.7 on 2023-12-01 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuario_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('articulo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo_sku', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=150)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('factor_compra', models.IntegerField()),
                ('factor_reparto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CanalCliente',
            fields=[
                ('canal_cliente_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('canal_cliente_descripcion', models.CharField(choices=[('Mayoristas', 'Mayoristas'), ('Cobertura', 'Cobertura'), ('Mercado', 'Mercado'), ('Institucionales', 'Institucionales')], default='M', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cliente_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nro_documento', models.CharField(max_length=12)),
                ('nombre_razon_social', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('canal_cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.canalcliente')),
            ],
        ),
        migrations.CreateModel(
            name='CondicionesVenta',
            fields=[
                ('condicion_venta', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('genera_credito', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nro_documento', models.CharField(max_length=11)),
                ('razon_social', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FormulaDetalle',
            fields=[
                ('formula_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipoPromocion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GruposProveedor',
            fields=[
                ('grupo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo_grupo', models.CharField(max_length=15)),
                ('grupo_descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField()),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.empresa')),
                ('responsable_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_proveedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LineasArticulos',
            fields=[
                ('linea_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo_linea', models.CharField(max_length=15)),
                ('linea_descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField()),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.gruposproveedor')),
                ('responsable_linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('marca_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo_marca', models.CharField(max_length=14)),
                ('marca_nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='NotasVenta',
            fields=[
                ('nota_venta_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nro_pedido', models.CharField(max_length=25, null=True)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('plazo', models.IntegerField()),
                ('tipo_documento', models.CharField(max_length=2)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.clientes')),
                ('condicion_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.condicionesventa')),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('promocion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TiposIdentificacion',
            fields=[
                ('tipo_identificacion_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('tipo_identificacion_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TiposPedido',
            fields=[
                ('tipo_pedido_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('tipo_pedido_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('unidad_medida_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('unidad_nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='VentaFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.formuladetalle')),
                ('nota_venta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.notasventa')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('vendedor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('vendedor_codigo', models.CharField(max_length=15)),
                ('nro_documento', models.CharField(max_length=11)),
                ('nombres', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('correo_electronico', models.EmailField(max_length=255)),
                ('nro_movil', models.CharField(max_length=15)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.empresa')),
                ('tipo_identificacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.tiposidentificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('sucursal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='SublineasArticulos',
            fields=[
                ('sublinea_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo_sublinea', models.CharField(max_length=15)),
                ('sublinea_descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
                ('linea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.lineasarticulos')),
            ],
        ),
        migrations.AddField(
            model_name='notasventa',
            name='sucursal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.sucursales'),
        ),
        migrations.AddField(
            model_name='notasventa',
            name='tipo_pedido_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.tipospedido'),
        ),
        migrations.CreateModel(
            name='ItemsNotaVenta',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nro_item', models.IntegerField(null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_item_bruto', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('factor_descuento', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('descuento_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_item', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('es_bonificacion', models.BooleanField(default=False)),
                ('articulo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.articulos')),
                ('nota_venta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.notasventa')),
            ],
        ),
        migrations.AddField(
            model_name='formuladetalle',
            name='promocion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.promociones'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tipo_identificacionC_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.tiposidentificacion'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='empresa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.empresa'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='grupo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.gruposproveedor'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='linea_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.lineasarticulos'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='marca_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.marcas'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='sublinea_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.sublineasarticulos'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='unidad_medida_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonificacion.unidadesmedida'),
        ),
    ]
