# Generated by Django 4.2.7 on 2023-12-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsnotaventa',
            name='factor_descuento',
            field=models.IntegerField(),
        ),
    ]
