# Generated by Django 4.2.7 on 2023-12-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuentos',
            old_name='sin_limite_cantidad_maxima_productos',
            new_name='rango_productos',
        ),
        migrations.RenameField(
            model_name='descuentos',
            old_name='sin_limite_cantidad_total_venta',
            new_name='rango_venta',
        ),
        migrations.RemoveField(
            model_name='descuentos',
            name='seleccionar_cantidad_total_venta',
        ),
        migrations.AddField(
            model_name='descuentos',
            name='sin_limite_productos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='descuentos',
            name='sin_limite_venta',
            field=models.BooleanField(default=False),
        ),
    ]
