# Generated by Django 4.2.7 on 2023-12-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificacion', '0002_rename_sin_limite_cantidad_maxima_productos_descuentos_rango_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos',
            name='cantidad_maxima_productos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descuentos',
            name='cantidad_total_maxima_venta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
