# Generated by Django 4.2.7 on 2023-12-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificacion', '0002_alter_itemsnotaventa_factor_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsnotaventa',
            name='factor_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
