# Generated by Django 4.2.7 on 2023-12-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificacion', '0003_alter_itemsnotaventa_factor_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos',
            name='sin_limite_productos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='descuentos',
            name='sin_limite_venta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
